version: '3.8'

services:
  th_laravel :
    build:
      context: ./
      dockerfile: Dockerfile
    image: th_laravel_latest
    container_name: th_laravel
    working_dir: /var/www
    volumes:
      - .:/var/www
    environment:
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=0
    restart: unless-stopped
    privileged: true
    tty: true
    networks:
      - th_network

  th_nginx_proxy:
    image: nginx:stable-alpine
    container_name: th_nginx_latest
    restart: unless-stopped
    tty: true
    depends_on:
      - th_laravel
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - th_network

  th_db:
    image: mysql:8.0.21
    container_name: th_mysql_latest
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: thiio
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "33061:3306"
    volumes:
      - dbdata:/var/lib/mysql:delegated
    command:
      - --default-authentication-plugin=mysql_native_password
      - --sort_buffer_size=1073741824
      - --max_connections=1000
    networks:
      - th_network

  th_random_http_service:
    image: httpd:latest
    container_name: th_random_http_service
    restart: unless-stopped
    tty: true
    depends_on:
      - th_laravel
    ports:
      - "8080:80"
    networks:
      - th_network

volumes:
  dbdata:
    driver: local

networks:
  th_network:
    driver: bridge
